# Generated by Django 4.0.2 on 2023-06-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0068_lead_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_delay',
            name='achived',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
