# Generated by Django 4.0.2 on 2023-06-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0069_lead_delay_achived'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_delay',
            name='sub_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
