# Generated by Django 4.0.2 on 2023-06-24 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0071_rename_end_date_lead_delay_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_work',
            name='target_count',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='daily_leeds_exists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2023, 6, 24))),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ph_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('qualification', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('year_of_passout', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('collegename', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('internship', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('internship_institute', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('internship_topic', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('internship_start', models.DateField(blank=True, null=True)),
                ('internship_end', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('fresher_experience', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('previous_experience', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('register', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ex_duration', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('daily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.daily_work')),
            ],
        ),
    ]
